version: '2'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - uwsgi:/var/run/uwsgi/
      - dbsocket:/var/run/php-fpm/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - php
      - linebot-python

  php:
    build:
      context: .
      dockerfile: ./linebot-web/Dockerfile/
    environment:
      pass:
    volumes:
      - dbsocket:/var/run/php-fpm/

  linebot-python:
    build:
      context: .
      dockerfile: ./python-linebot/Dockerfile/
    environment:
      LINE_CHANNEL_SECRET:
      LINE_CHANNEL_ACCESS_TOKEN:
      pass:
    volumes:
      - uwsgi:/home/socket/

volumes:
  dbsocket:
  uwsgi:
