version: '2'
services:
  nginx:
    image: nginx:1.23.0
    volumes:
      - uwsgi:/var/run/uwsgi/
      - dbsocket:/var/run/php-fpm/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./linebot-web:/var/www/html
    ports:
      - "8888:8888"
    environment:
      TZ: Asia/Tokyo
    user: nginx:nginx
    depends_on:
      - php
      - linebot-python
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: ./linebot-web/Dockerfile/
    environment:
      pass:
    volumes:
      - dbsocket:/var/run/php-fpm/
    restart: unless-stopped

  linebot-python:
    build:
      context: .
      dockerfile: ./python-linebot/Dockerfile/
    environment:
      LINE_CHANNEL_SECRET:
      LINE_CHANNEL_ACCESS_TOKEN:
      pass:
    volumes:
      - uwsgi:/home/socket/
    restart: unless-stopped
      
volumes:
  dbsocket:
  uwsgi:
