version: '2'
services:
  nginx:
    image: nginx:1.21
    volumes:
      - uwsgi:/var/run/uwsgi/
      - dbsocket:/var/run/php-fpm/
      - ./default.conf:/etc/nginx/nginx.conf
      - ./linebot-web:/var/www/html
      - ./server.crt:/etc/nginx/server.crt
      - ./server.key:/etc/nginx/server.key
    ports:
      - "443:4443"
    environment:
      TZ: Asia/Tokyo
    user: nginx:nginx
    depends_on:
      - php
      - linebot-python

  php:
    build:
      context: .
      dockerfile: ./linebot-web/Dockerfile/
    environment:
      pass:
    volumes:
      - dbsocket:/var/run/php-fpm/

  linebot-python:
    build:
      context: .
      dockerfile: ./python-linebot/Dockerfile/
    environment:
      LINE_CHANNEL_SECRET:
      LINE_CHANNEL_ACCESS_TOKEN:
      pass:
    volumes:
      - uwsgi:/home/socket/

volumes:
  dbsocket:
  uwsgi:
